name: Setup WordPress and Run Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  setup-wordpress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install MySQL
        run: |
          # Update package list and install MySQL
          sudo apt-get update
          sudo apt-get install -y mysql-server

          # Start MySQL service
          sudo systemctl start mysql

          # Enable MySQL to start on boot
          sudo systemctl enable mysql

          # Set the root password
          sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'password';"

          # Reload privileges to apply the new root password
          sudo mysql -e "FLUSH PRIVILEGES;"

      - name: Create WordPress Database
        run: |
          # Create the WordPress database with the root password
          sudo mysql -u root -ppassword -e "CREATE DATABASE wordpress;"

      - name: Install PHP and Dependencies
        run: |
          # Install PHP and necessary extensions for WordPress
          sudo apt-get install -y php php-mysql php-cli php-curl php-xml php-mbstring

      - name: Install WordPress
        run: |
          # Download WordPress
          wget https://wordpress.org/latest.tar.gz

          # Extract WordPress
          tar -xvzf latest.tar.gz

          # Move WordPress files to /var/www/html
          sudo mv wordpress /var/www/html/wordpress

          # Set permissions
          sudo chown -R www-data:www-data /var/www/html/wordpress

      - name: Configure WordPress wp-config.php
        run: |
          # Configure WordPress to use the database
          cp /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php

          # Update wp-config.php to set database info
          sudo sed -i "s/database_name_here/wordpress/" /var/www/html/wordpress/wp-config.php
          sudo sed -i "s/username_here/root/" /var/www/html/wordpress/wp-config.php
          sudo sed -i "s/password_here/password/" /var/www/html/wordpress/wp-config.php

      - name: Start Apache2 and MySQL Services
        run: |
          # Install and start Apache server for WordPress
          sudo apt-get install -y apache2
          sudo systemctl start apache2
          sudo systemctl enable apache2

          # Restart MySQL service to apply changes
          sudo systemctl restart mysql

      - name: Install Cypress
        run: |
          # Install Node.js and npm
          sudo apt-get install -y nodejs npm

          # Install Cypress
          npm install cypress

      - name: Run Cypress Tests
        run: |
          # Run Cypress tests after WordPress setup
          npx cypress run --headless --browser chrome

      - name: Share Cypress Test Results
        run: |
          # After test completion, print the results
          echo "Cypress tests completed successfully"
