name: Setup WordPress and Run Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  wordpress-setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        tools: composer

    - name: Install MySQL
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-server
        sudo systemctl start mysql
        sudo mysql -e "CREATE DATABASE wordpress;"
        sudo mysql -e "CREATE USER 'wordpress'@'localhost' IDENTIFIED BY 'password';"
        sudo mysql -e "GRANT ALL PRIVILEGES ON wordpress.* TO 'wordpress'@'localhost';"
        sudo mysql -e "FLUSH PRIVILEGES;"

    - name: Install WordPress
      run: |
        curl -O https://wordpress.org/latest.tar.gz
        tar -xvf latest.tar.gz
        mv wordpress /var/www/html/
        sudo chown -R www-data:www-data /var/www/html/wordpress
        sudo chmod -R 755 /var/www/html/wordpress
        cp /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php
        sed -i "s/database_name_here/wordpress/" /var/www/html/wordpress/wp-config.php
        sed -i "s/username_here/wordpress/" /var/www/html/wordpress/wp-config.php
        sed -i "s/password_here/password/" /var/www/html/wordpress/wp-config.php
        sudo systemctl restart apache2

    - name: Start Apache on port 8080
      run: |
        sudo sed -i 's/80/8080/' /etc/apache2/ports.conf
        sudo systemctl restart apache2

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Cypress
      run: npm install cypress --save-dev

    - name: Run Cypress Tests
      run: |
        npx cypress run --spec "cypress/integration/login_spec.js"
      env:
        CYPRESS_BASE_URL: "http://localhost:8080/wordpress"

    - name: Upload Cypress Test Results
      uses: actions/upload-artifact@v3
      with:
        name: cypress-test-results
        path: cypress/reports
